# Generated by Django 3.1.5 on 2021-02-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.IntegerField(verbose_name='길드ID')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('dttm', models.DateTimeField(verbose_name='시각')),
                ('max_attendee', models.IntegerField(null=True, verbose_name='최대인원')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'db_table': 'PlanTable',
            },
        ),
    ]
