# Generated by Django 3.1.5 on 2021-02-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='attendee',
            field=models.ManyToManyField(related_name='참가자', to='baseApp.User'),
        ),
    ]
