# Generated by Django 3.1.5 on 2021-02-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='유저ID')),
                ('name', models.CharField(max_length=128, verbose_name='이름')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'UserTable',
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False, verbose_name='길드ID')),
                ('name', models.CharField(max_length=128, verbose_name='이름')),
                ('user', models.ManyToManyField(related_name='유저', to='baseApp.User')),
            ],
            options={
                'verbose_name': 'guild',
                'verbose_name_plural': 'guilds',
                'db_table': 'GuildTable',
            },
        ),
    ]
